routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
	return view('auth.login');
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('roles','RoleController');
Route::post('roles/update','RoleController@update')->name('update.roles');
Route::post('roles/edits','RoleController@edit')->name('roles.edits');
Route::any('roles/status','RoleController@status')->name('role.status');

Route::resource('user','UserController');
Route::post('user/delete','UserController@delete')->name('delete');
Route::post('user/indexs', 'UserController@index')->name('user.indexs');
Route::post('check/email','UserController@checkEmail')->name('check.email');
Route::any('user/status','UserController@status')->name('user.status');

Route::resource('admin','AdminController');
Route::post('admin/delete','AdminController@delete')->name('delete');
Route::post('check/admin/email','AdminController@checkEmail')->name('check.adminEmail');
Route::any('admin/status','AdminController@status')->name('admin.status');

Route::resource('banner','BannerController');
Route::post('banner/update','BannerController@update')->name('update.banner');
Route::post('banner/edits','BannerController@edit')->name('edits');
Route::any('banner/status','BannerController@status')->name('banner.status');

Route::resource('category','CategoryController');
Route::post('category/update','CategoryController@update')->name('update.category');
Route::post('category/edits','CategoryController@edit')->name('category.edits');
Route::any('category/status','CategoryController@status')->name('category.status');
Route::post('category/indexs', 'CategoryController@index')->name('category.indexs');
Route::post('category/delete','CategoryController@delete')->name('delete.category');
Route::post('check/catName','CategoryController@checkCatName')->name('check.catName');

Route::resource('subCategory','SubcategoryController');
Route::post('subCategory/update','SubcategoryController@update')->name('update.subCategory');
Route::post('subCategory/edits','SubcategoryController@edit')->name('subCategory.edits');
Route::any('subCategory/status','SubcategoryController@status')->name('subCategory.status');
Route::post('subCategory/indexs', 'SubcategoryController@index')->name('subCategory.indexs');
Route::post('subCategory/delete','SubcategoryController@delete')->name('delete.subCategory');
Route::post('check/subCatName','SubcategoryController@checkSubCatName')->name('check.subCatName');

Route::resource('course','CourseController');
Route::post('course/delete','CourseController@delete')->name('course.delete');
Route::any('course/status','CourseController@status')->name('course.status');
Route::any('course/homestatus','CourseController@homestatus')->name('course.homestatus');
Route::post('get/subCate', 'CourseController@getSubcate')->name('get.subCate');
Route::post('course/changeCommision', 'CourseController@changeCommision')->name('course.changeCommision');

Route::resource('staticPage','StaticPageController');
Route::post('staticPage/delete','StaticPageController@delete')->name('staticPage.delete');
Route::post('staticPage/indexs', 'StaticPageController@index')->name('staticPage.indexs');
Route::any('staticPage/status','StaticPageController@status')->name('staticPage.status');
Route::post('check/title','StaticPageController@checkTitle')->name('check.title');

Route::resource('testimonials','TestimonialsController');
Route::post('testimonials/delete','TestimonialsController@delete')->name('testimonials.delete');
Route::post('testimonials/indexs', 'TestimonialsController@index')->name('testimonials.indexs');
Route::any('testimonials/status','TestimonialsController@status')->name('testimonials.status');

Route::resource('profile','ProfileController');
Route::get('changePassword','ProfileController@changePassword')->name('changePassword');
Route::post('check/password','ProfileController@checkPassword')->name('check.password');

Route::resource('session','SessionController');
Route::post('session/delete','SessionController@delete')->name('session.delete');
Route::any('session/status','SessionController@status')->name('session.status');

Route::resource('review','ReviewController');
Route::post('review/update','ReviewController@update')->name('update.review');
Route::post('review/edits','ReviewController@edit')->name('review.edits');
Route::any('review/status','ReviewController@status')->name('review.status');
Route::post('review/indexs', 'ReviewController@index')->name('review.indexs');
Route::post('review/delete','ReviewController@delete')->name('delete.review');

Route::resource('payment','PaymentController');
Route::resource('redemption','RedemptionController');

app/Models/Testimonials.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Testimonials extends Model
{
	use SoftDeletes;
    protected $table = 'testimonials';
	protected $primaryKey = 'id';
	protected $guarded = ['id'];
}

app/Http/Controllers/TestimonialsController.php
<?php



namespace App\Http\Controllers;

use Illuminate\Support\Facades\Hash;

use Illuminate\Http\Request;

use App\Models\Testimonials;

use Str;

use DB;



class TestimonialsController extends Controller

{

	/**

	 * Display a listing of the resource.

	 *

	 * @return \Illuminate\Http\Response

	 */

	

	public function __construct(FrontUser $s)

	{

		$this->middleware('auth');

	}



	public function index(Request $request)

	{

		$data['title'] = 'User';

		$data['data'] = Testimonials::where('active',1)->get();

		return view('testimonials.index')->with($data);
	}



	/**

	 * Show the form for creating a new resource.

	 *

	 * @return \Illuminate\Http\Response

	 */

	public function create()

	{

		$data['title'] = "Testimonials";

		return view('testimonials.create')->with($data);

	}



	/**

	 * Store a newly created resource in storage.

	 *

	 * @param  \Illuminate\Http\Request  $request

	 * @return \Illuminate\Http\Response

	 */

	public function store(Request $request)

	{

		$param = $request->all();

		$create = Testimonials::create($param);

		if($create)

		{

			return response()->json(['status' => 'success']);

		}

		else

		{

			return response()->json(['status' => 'error']);

		}

	}





	public function status(Request $request)

	{

		$user = Testimonials::where('id',$request->get('id'))->value('active');

		if($user == 1)

		{

			$update = Testimonials::where('id',$request->get('id'))->update(['active' => 0]);

		}

		if($user == 0)

		{

			$update = Testimonials::where('id',$request->get('id'))->update(['active' => 1]);

		}

		if($update)

		{

			return response()->json(['status' => 'status_changed']);

		}

	}

	public function show($id)
	{

	}

	public function edit($id)

	{

		$data['title'] = 'Testimonials';

		$data['edit'] = Testimonials::FindOrFail($id);

		return view('testimonials.edit')->with($data);

	}


	public function update(Request $request, $id)

	{

		$param = $request->all();

		$update = Testimonials::where('id',$id)->update($param);

		if($update)

		{

			return response()->json(['status' => 'success']);

		}

		else

		{

			return response()->json(['status' => 'error']);

		}

	}



	/**

	 * Remove the specified resource from storage.

	 *

	 * @param  int  $id

	 * @return \Illuminate\Http\Response

	 */

	public function delete(Request $request)

	{

		$delete = Testimonials::where('id',$request->get('id'))->delete();

		if ($delete) 

		{

			return response()->json(['status' => 'success']);

		}

	}

}

resources/views/testimonials/create.blade.php
@extends('main')

@section('content')



<script src="{{ asset('assets/plugins/ckeditor/ckeditor.js') }}" type="text/javascript"></script>


<link href="{{ asset('assets/plugins/custom/datatables/datatables.bundle.css')}}" rel="stylesheet" type="text/css" />



<link href="{{ asset('sweetalert/dist/sweetalert.css')}}" rel="stylesheet" type="text/css" />

<div class="kt-content  kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor" id="kt_content"><br/>

	<div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">

		<div class="kt-portlet kt-portlet--mobile">

			<div class="kt-portlet__head kt-portlet__head--lg">

				<div class="kt-portlet__head-label">

					<span class="kt-portlet__head-icon">

						<i class="kt-font-brand flaticon2-line-chart"></i>

					</span>

					<h3 class="kt-portlet__head-title">

						Add {{ $title }}

					</h3>

				</div>

			</div>

			<div class="kt-portlet__body">

				<div id="kt_table_1_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">

					<form class="kt-form add__form" id="add__form" method="post">

						@csrf

						<div class="row">

							<div class="col-sm-5">

								<label>Name<code>*</code></label>

								<input type="text" class="form-control" name="name" id="name" placeholder="Enter Name" autocomplete="off">

							</div>

						</div>



						<div class="row">

							<div class="col-sm-12">

								<label>Description<code>*</code></label>

								<textarea class="form-control" id="description" name="description" rows="8"></textarea>

							</div>

						</div>



						<div class="kt-portlet__foot">

							<div class="kt-form__actions">

								<button type="button" class="btn btn-brand" id="save">Submit</button>

								<a href="{{route('testimonials.index')}}" class="btn btn-dark">Cancel</a>

							</div>

						</div>

					</form>

				</div>

			</div>

		</div>

	</div>



</div>

<!-- <script type="text/javascript">
	CKEDITOR.replace( 'description' );
</script> -->

<script>

	$(".add__form").validate({

		rules:

		{

			name:{required: true},
			description:{required: true}
			
		},

		messages:
		{
			name:{required:"Please enter name"},
			description:{required:"Please enter description"}
		}

	});



	$("#save").on("click", function (e)

	{

		e.preventDefault();

		if ($(".add__form").valid())

		{
			// for ( instance in CKEDITOR.instances ) {
			// 	CKEDITOR.instances.description.updateElement();
			// }
			$.ajax({

				type: "POST",

				url: "{{ route('testimonials.store') }}",

				data: new FormData($('.add__form')[0]),

				processData: false,

				contentType: false,

				success: function (data)

				{

					if (data.status === 'success') 

					{

						toastr.options.timeOut = 3000;

						toastr.options.fadeOut = 3000;

						toastr.options.progressBar = true;

						toastr.options.onHidden = function(){

							window.location = "{{ route('testimonials.index') }}"

						};



						toastr["success"]("{{$title}} Added Successfully", "Success");

					}

					else if(data.status === 'error') 

					{

						toastr.options.timeOut = 3000;

						toastr.options.fadeOut = 3000;

						toastr.options.progressBar = true;



						toastr["error"]("Opps.. Something Went Wrong.!", "Error");

					}

				}

			});

		}

		else

		{

			e.preventDefault();

		}

	});

</script>

@stop

resources/views/testimonials/edit.blade.php
@extends('main')

@section('content')



<script src="{{ asset('assets/plugins/ckeditor/ckeditor.js') }}" type="text/javascript"></script>


<link href="{{ asset('assets/plugins/custom/datatables/datatables.bundle.css')}}" rel="stylesheet" type="text/css" />



<link href="{{ asset('sweetalert/dist/sweetalert.css')}}" rel="stylesheet" type="text/css" />





<div class="kt-content  kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor" id="kt_content"><br/>





	<div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">

		<div class="kt-portlet kt-portlet--mobile">

			<div class="kt-portlet__head kt-portlet__head--lg">

				<div class="kt-portlet__head-label">

					<span class="kt-portlet__head-icon">

						<i class="kt-font-brand flaticon2-line-chart"></i>

					</span>

					<h3 class="kt-portlet__head-title">

						Add {{ $title }}

					</h3>

				</div>

			</div>

			<div class="kt-portlet__body">

				<div id="kt_table_1_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">

					<form class="kt-form edit__form" id="edit__form" method="POST">

						@csrf

						@method('PUT')
						
						<div class="row">

							<div class="col-sm-5">

								<label>Name<code>*</code></label>

								<input type="text" class="form-control" name="name" id="name" placeholder="Enter Name" autocomplete="off" value="{{ $edit->name }}">

							</div>

						</div>



						<div class="row">

							<div class="col-sm-12">

								<label>Description<code>*</code></label>

								<textarea class="form-control" id="description" name="description" rows="8">{{ $edit->description }}</textarea>

							</div>

						</div>



						<div class="kt-portlet__foot">

							<div class="kt-form__actions">

								<button type="button" class="btn btn-brand" id="save">Submit</button>

								<a href="{{route('testimonials.index')}}" class="btn btn-dark">Cancel</a>

							</div>

						</div>

					</form>

				</div>

			</div>

		</div>

	</div>



</div>

<!-- <script type="text/javascript">
	CKEDITOR.replace( 'description' );
</script>
 -->
<script>

	$(".edit__form").validate({
		rules:
		{
			name:{required: true},
			description:{required: true}
		},
		messages:
		{
			name:{required:"Please enter name"},
			description:{required:"Please enter description"}
		}
	});

	$.ajaxSetup({

		headers: {

			'X-CSRF-TOKEN': $('meta[name="_token"]').attr('content')

		}

	});

	$("#save").on("click", function (e)

	{

		e.preventDefault();

		if ($(".edit__form").valid())

		{
			// for ( instance in CKEDITOR.instances ) {
			// 	CKEDITOR.instances.description.updateElement();
			// }
			$.ajax({

				type: "POST",

				url: "{{ route('testimonials.update', array($edit->id)) }}",

				data: new FormData($('.edit__form')[0]),

				processData: false,

				contentType: false,

				success: function (data)

				{

					if (data.status === 'success') 

					{

						toastr.options.timeOut = 3000;

						toastr.options.fadeOut = 3000;

						toastr.options.progressBar = true;

						toastr.options.onHidden = function(){

							window.location = "{{ route('testimonials.index') }}"

						};



						toastr["success"]("{{$title}} Added Successfully", "Success");

					}

					else if(data.status === 'error') 

					{

						toastr.options.timeOut = 3000;

						toastr.options.fadeOut = 3000;

						toastr.options.progressBar = true;



						toastr["error"]("Opps.. Something Went Wrong.!", "Error");

					}

				}

			});

		}

		else

		{

			e.preventDefault();

		}

	});

</script>

@stop

resources/views/testimonials/index.blade.php
@extends('main')
@section('content')

<div class="kt-content  kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor" id="kt_content"><br/>
	<div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">
		<div class="kt-portlet kt-portlet--mobile">
			<div class="kt-portlet__head kt-portlet__head--lg">
				<div class="kt-portlet__head-label">
					<span class="kt-portlet__head-icon">
						<i class="kt-font-brand flaticon2-line-chart"></i>
					</span>
					<h3 class="kt-portlet__head-title">
						{{ $title }} List
					</h3>
				</div>
				<div class="kt-portlet__head-toolbar">
					<div class="kt-portlet__head-wrapper">
						
						<div class="kt-portlet__head-actions">
							<a href="{{ route('testimonials.create') }}" class="btn btn-brand btn-elevate btn-icon-sm">
								<i class="la la-plus"></i>
								Add {{$title}}
							</a>
						</div>
						
					</div>
				</div>
			</div>
			<div class="kt-portlet__body">
				<div id="kt_table_1_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">

					<div class="row">
						<div class="col-sm-12" id="user_list_table">
							<table class="table table-striped- table-bordered table-hover table-checkable dataTable no-footer dtr-inline" id="user_list" role="grid" aria-describedby="kt_table_1_info">
								@csrf

								<thead>
									<tr role="row">
										<th>No</th>
										<th>Name</th>
										<th>Description</th>
										<th>Activate Status</th>
										<th>Actions</th>
									</tr>
								</thead>
								<tbody>

									@if(!empty($data))
									<?php $count = 1; ?>
									@foreach($data as $dt)
									<tr>
										<td>{{ $count++ }}</td>
										<td>{{ ucfirst($dt->name) }}</td>
										<td>{{ $dt->description }}</td>
										<td>
											<span class="kt-switch kt-switch--sm">
												<label>
													<input type="checkbox" @if($dt->active == 1) checked @endif onchange="status('{{ $dt->id }}')" name="">
													<span></span>
												</label>
											</span>
										</td>
										<td>
											<a href="{{route('testimonials.edit',$dt->id)}}" class="btn btn-sm btn-clean btn-icon btn-icon-md" title="Edit" style="background: #968cbd;">
												<i class="la la-edit" style="color: white !important;"></i>
											</a>
											<input type="hidden" value="{{ $dt->id }}" name="delete_user_id" id="delete_user_id">

											<button class="btn btn-sm btn-clean btn-icon btn-icon-md" id="delete_user" style="background-color: red;" data-toggle="tooltip" title="Delete">
												<i class="la la-trash" style="color: #ffffff"></i>
											</button>
										</td>
									</tr>
									@endforeach
									@endif
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script>
	$(document).ready(function() {
		$('#user_list').DataTable();
	});
</script>
<script>

	function status(id){
		$.ajax({
			type:'POST',
			url:"{{route('testimonials.status')}}",
			data:{
				'_token' : $('input[name="_token"]').val(),
				'id':id
			},
			success:function(data){
				if (data.status === 'status_changed') 
				{
					toastr.options.timeOut = 1500;
					toastr.options.fadeOut = 1500;
					toastr.options.progressBar = true;
					toastr.options.onHidden = function(){
					};

					toastr["success"]("Activation Status Changed", "Success");
				}
			}
		});

	}

	$(document).ready(function() {

		$(document).on('click', '#delete_user', function ()
		{
			var obj = $(this);
			var id = $(this).closest('td').find("#delete_user_id").val();

			swal({
				title: "Are you sure?",
				text: "You will not be able recover this record",
				type: "warning",
				showCancelButton: true,
				confirmButtonColor: "#DD6B55",
				confirmButtonText: "Yes delete it!",
				closeOnConfirm: false
			},
			function () {
				$.ajax({
					type: "post",
					url: '{{ route('testimonials.delete') }}',
					data: {
						'_token': $('input[name="_token"]').val(),
						'id': id
					},
					cache: false,
					success: function (data)
					{
						obj.closest('tr').remove();
					}
				});
				swal("Deleted", "{{ $title }} has been deleted.", "success");
			});
		});
	});

</script>

@stop