routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
	return view('auth.login');
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('roles','RoleController');
Route::post('roles/update','RoleController@update')->name('update.roles');
Route::post('roles/edits','RoleController@edit')->name('roles.edits');
Route::any('roles/status','RoleController@status')->name('role.status');

Route::resource('user','UserController');
Route::post('user/delete','UserController@delete')->name('delete');
Route::post('user/indexs', 'UserController@index')->name('user.indexs');
Route::post('check/email','UserController@checkEmail')->name('check.email');
Route::any('user/status','UserController@status')->name('user.status');

Route::resource('admin','AdminController');
Route::post('admin/delete','AdminController@delete')->name('delete');
Route::post('check/admin/email','AdminController@checkEmail')->name('check.adminEmail');
Route::any('admin/status','AdminController@status')->name('admin.status');

Route::resource('banner','BannerController');
Route::post('banner/update','BannerController@update')->name('update.banner');
Route::post('banner/edits','BannerController@edit')->name('edits');
Route::any('banner/status','BannerController@status')->name('banner.status');

Route::resource('category','CategoryController');
Route::post('category/update','CategoryController@update')->name('update.category');
Route::post('category/edits','CategoryController@edit')->name('category.edits');
Route::any('category/status','CategoryController@status')->name('category.status');
Route::post('category/indexs', 'CategoryController@index')->name('category.indexs');
Route::post('category/delete','CategoryController@delete')->name('delete.category');
Route::post('check/catName','CategoryController@checkCatName')->name('check.catName');

Route::resource('subCategory','SubcategoryController');
Route::post('subCategory/update','SubcategoryController@update')->name('update.subCategory');
Route::post('subCategory/edits','SubcategoryController@edit')->name('subCategory.edits');
Route::any('subCategory/status','SubcategoryController@status')->name('subCategory.status');
Route::post('subCategory/indexs', 'SubcategoryController@index')->name('subCategory.indexs');
Route::post('subCategory/delete','SubcategoryController@delete')->name('delete.subCategory');
Route::post('check/subCatName','SubcategoryController@checkSubCatName')->name('check.subCatName');

Route::resource('course','CourseController');
Route::post('course/delete','CourseController@delete')->name('course.delete');
Route::any('course/status','CourseController@status')->name('course.status');
Route::any('course/homestatus','CourseController@homestatus')->name('course.homestatus');
Route::post('get/subCate', 'CourseController@getSubcate')->name('get.subCate');
Route::post('course/changeCommision', 'CourseController@changeCommision')->name('course.changeCommision');

Route::resource('staticPage','StaticPageController');
Route::post('staticPage/delete','StaticPageController@delete')->name('staticPage.delete');
Route::post('staticPage/indexs', 'StaticPageController@index')->name('staticPage.indexs');
Route::any('staticPage/status','StaticPageController@status')->name('staticPage.status');
Route::post('check/title','StaticPageController@checkTitle')->name('check.title');

Route::resource('testimonials','TestimonialsController');
Route::post('testimonials/delete','TestimonialsController@delete')->name('testimonials.delete');
Route::post('testimonials/indexs', 'TestimonialsController@index')->name('testimonials.indexs');
Route::any('testimonials/status','TestimonialsController@status')->name('testimonials.status');

Route::resource('profile','ProfileController');
Route::get('changePassword','ProfileController@changePassword')->name('changePassword');
Route::post('check/password','ProfileController@checkPassword')->name('check.password');

Route::resource('session','SessionController');
Route::post('session/delete','SessionController@delete')->name('session.delete');
Route::any('session/status','SessionController@status')->name('session.status');

Route::resource('review','ReviewController');
Route::post('review/update','ReviewController@update')->name('update.review');
Route::post('review/edits','ReviewController@edit')->name('review.edits');
Route::any('review/status','ReviewController@status')->name('review.status');
Route::post('review/indexs', 'ReviewController@index')->name('review.indexs');
Route::post('review/delete','ReviewController@delete')->name('delete.review');

Route::resource('payment','PaymentController');
Route::resource('redemption','RedemptionController');

resources/views/admin/create.blade.php
@extends('main')
@section('content')


<link href="{{ asset('assets/plugins/custom/datatables/datatables.bundle.css')}}" rel="stylesheet" type="text/css" />

<link href="{{ asset('sweetalert/dist/sweetalert.css')}}" rel="stylesheet" type="text/css" />


<div class="kt-content  kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor" id="kt_content"><br/>


	<div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">
		<div class="kt-portlet kt-portlet--mobile">
			<div class="kt-portlet__head kt-portlet__head--lg">
				<div class="kt-portlet__head-label">
					<span class="kt-portlet__head-icon">
						<i class="kt-font-brand flaticon2-line-chart"></i>
					</span>
					<h3 class="kt-portlet__head-title">
						Add {{ $title }}
					</h3>
				</div>
			</div>
			<div class="kt-portlet__body">
				<div id="kt_table_1_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
					<form class="kt-form add__form" id="add__form" method="post">
						@csrf
						<div class="row">
							<div class="col-sm-4">
								<label>First Name<code>*</code></label>
								<input type="text" class="form-control" name="name" id="name" placeholder="Enter First Name" autocomplete="off">
							</div>
							<div class="col-sm-4">
								<label>Last Name<code>*</code></label>
								<input type="text" class="form-control" name="lname" id="lname" placeholder="Enter Last Name" autocomplete="off">
							</div>
							<div class="col-sm-4">
								<label>Email<code>*</code></label>
								<input type="text" class="form-control" name="email" id="email" placeholder="Enter Email" autocomplete="off">
							</div>
							<div class="col-sm-4">
								<label>Password<code>*</code></label>
								<input type="password" class="form-control" name="password" id="password" placeholder="Enter Password" autocomplete="off">
							</div>
							<div class="col-sm-4">
								<label>Confirm Password<code>*</code></label>
								<input type="password" class="form-control" name="cPassword" id="cPassword" placeholder="Enter Confirm Password" autocomplete="off">
							</div>
							<div class="col-sm-4">
								<label>Mobile No.<code>*</code></label>
								<input type="text" class="form-control" name="contact" id="contact" placeholder="Enter Mobile No." autocomplete="off">
							</div>
						</div>
						<div class="kt-portlet__foot">
							<div class="kt-form__actions">
								<button type="button" class="btn btn-brand" id="save">Submit</button>
								<a href="{{route('user.index')}}" class="btn btn-dark">Cancel</a>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>

</div>

<script>
	$(".add__form").validate({
		rules:
		{
			name:{required:true},
			lname:{required:true},
			email:{
				required: true,
				email: true,
				remote: {
					url: "{{ route('check.adminEmail') }}",
					type: "post",
					dataType: 'json',
					data: {
						'_token': $('input[name="_token"]').val(),
						email: function() {
							return $( "#email" ).val();
						}
					}
				}
			},
			password:{required:true},
			cPassword:{required:true,equalTo:"#password"},
			contact:{required:true},
		},
		messages:
		{
			name:{required:"Please enter first name"},
			lname:{required:"Please enter last name"},
			email:{
				required:"Please enter email id",
				email:"Please enter valid formate",
				remote:"This email is already exist"
			},
			password:{required:"Please enter password"},
			cPassword:{required:"Please enter confirm password",equalTo:"Please enter same as password"},
			contact:{required:"Please enter mobile no."}
		}
	});

	$("#save").on("click", function (e)
	{
		e.preventDefault();
		if ($(".add__form").valid())
		{
			$.ajax({
				type: "POST",
				url: "{{ route('admin.store') }}",
				data: new FormData($('.add__form')[0]),
				processData: false,
				contentType: false,
				success: function (data)
				{
					if (data.status === 'success') 
					{
						toastr.options.timeOut = 3000;
						toastr.options.fadeOut = 3000;
						toastr.options.progressBar = true;
						toastr.options.onHidden = function(){
							window.location = "{{ route('admin.index') }}"
						};

						toastr["success"]("Admin Added Successfully", "Success");
					}
					else if(data.status === 'error') 
					{
						toastr.options.timeOut = 3000;
						toastr.options.fadeOut = 3000;
						toastr.options.progressBar = true;

						toastr["error"]("Opps.. Something Went Wrong.!", "Error");
					}
				}
			});
		}
		else
		{
			e.preventDefault();
		}
	});
</script>
@stop

resources/views/admin/edit.blade.php
@extends('main')
@section('content')


<link href="{{ asset('assets/plugins/custom/datatables/datatables.bundle.css')}}" rel="stylesheet" type="text/css" />

<link href="{{ asset('sweetalert/dist/sweetalert.css')}}" rel="stylesheet" type="text/css" />


<div class="kt-content  kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor" id="kt_content"><br/>


	<div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">
		<div class="kt-portlet kt-portlet--mobile">
			<div class="kt-portlet__head kt-portlet__head--lg">
				<div class="kt-portlet__head-label">
					<span class="kt-portlet__head-icon">
						<i class="kt-font-brand flaticon2-line-chart"></i>
					</span>
					<h3 class="kt-portlet__head-title">
						Add {{ $title }}
					</h3>
				</div>
			</div>
			<div class="kt-portlet__body">
				<div id="kt_table_1_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
					<form class="kt-form edit__form" id="edit__form" method="POST">
						@csrf
						@method('PUT')
						<input type="hidden" id="user_id" value="{{ $edit->id }}">
						<div class="row">
							<div class="col-sm-4">
								<label>First Name<code>*</code></label>
								<input type="text" class="form-control" name="name" id="name" placeholder="Enter First Name" autocomplete="off" value="{{ $edit->name }}">
							</div>
							<div class="col-sm-4">
								<label>Last Name<code>*</code></label>
								<input type="text" class="form-control" name="lname" id="lname" placeholder="Enter Last Name" autocomplete="off" value="{{ $edit->lname }}">
							</div>
							<div class="col-sm-4">
								<label>Email<code>*</code></label>
								<input type="text" class="form-control" name="email" id="email" placeholder="Enter Email" autocomplete="off" value="{{ $edit->email }}">
							</div>
							<div class="col-sm-4">
								<label>Mobile No.<code>*</code></label>
								<input type="text" class="form-control" name="contact" id="contact" placeholder="Enter Mobile No." autocomplete="off" value="{{ $edit->contact }}">
							</div>
						</div>
						<div class="kt-portlet__foot">
							<div class="kt-form__actions">
								<button type="button" class="btn btn-brand" id="save">Submit</button>
								<a href="{{route('admin.index')}}" class="btn btn-dark">Cancel</a>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>

</div>

<script>
	$(".edit__form").validate({
		rules:
		{
			role_id:{required:true},
			name:{required:true},
			lname:{required:true},
			email:{
				required: true,
				email: true,
				remote: {
					url: "{{ route('check.adminEmail') }}",
					type: "post",
					dataType: 'json',
					data: {
						'_token': $('input[name="_token"]').val(),
						id: function() {
							return $( "#user_id" ).val();
						},
						email: function() {
							return $( "#email" ).val();
						}
					}
				}
			},
			contact:{required:true},
			school_name:{required:true}
		},
		messages:
		{
			role_id:{required:"Please select role"},
			name:{required:"Please enter first name"},
			lname:{required:"Please enter last name"},
			email:{
				required:"Please enter email id",
				email:"Please enter valid formate",
				remote:"This email is already exist"
			},
			contact:{required:"Please enter mobile no."},
			school_name:{required:"Please enter school name"}
		}
	});

	$.ajaxSetup({
		headers: {
			'X-CSRF-TOKEN': $('meta[name="_token"]').attr('content')
		}
	});

	$("#save").on("click", function (e)
	{
		e.preventDefault();
		if ($(".edit__form").valid())
		{
			$.ajax({
				type: "POST",
				url: "{{ route('admin.update', array($edit->id)) }}",
				data: new FormData($('.edit__form')[0]),
				processData: false,
				contentType: false,
				success: function (data)
				{
					if (data.status === 'success') 
					{
						toastr.options.timeOut = 3000;
						toastr.options.fadeOut = 3000;
						toastr.options.progressBar = true;
						toastr.options.onHidden = function(){
							window.location = "{{ route('admin.index') }}"
						};

						toastr["success"]("User Updated Successfully", "Success");
					}
					else if(data.status === 'error') 
					{
						toastr.options.timeOut = 3000;
						toastr.options.fadeOut = 3000;
						toastr.options.progressBar = true;

						toastr["error"]("Opps.. Something Went Wrong.!", "Error");
					}
				}
			});
		}
		else
		{
			e.preventDefault();
		}
	});
</script>
@stop

resources/views/admin/index.blade.php
@extends('main')
@section('content')

<div class="kt-content  kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor" id="kt_content"><br/>
	<div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">
		<div class="kt-portlet kt-portlet--mobile">
			<div class="kt-portlet__head kt-portlet__head--lg">
				<div class="kt-portlet__head-label">
					<span class="kt-portlet__head-icon">
						<i class="kt-font-brand flaticon2-line-chart"></i>
					</span>
					<h3 class="kt-portlet__head-title">
						{{ $title }} List
					</h3>
				</div>
				<div class="kt-portlet__head-toolbar">
					<div class="kt-portlet__head-wrapper">
						
						<div class="kt-portlet__head-actions">
							<a href="{{ route('admin.create') }}" class="btn btn-brand btn-elevate btn-icon-sm">
								<i class="la la-plus"></i>
								Add {{$title}}
							</a>
						</div>
						
					</div>
				</div>
			</div>
			<div class="kt-portlet__body">
				<div id="kt_table_1_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">

					<div class="row">
						<div class="col-sm-12" id="user_list_table">
							<table class="table table-striped- table-bordered table-hover table-checkable dataTable no-footer dtr-inline" id="user_list" role="grid" aria-describedby="kt_table_1_info">
								@csrf

								<thead>
									<tr role="row">
										<th>No</th>
										<th>Name</th>
										<th>Email</th>
										<th>Activate Status</th>
										<th>Actions</th>
									</tr>
								</thead>
								<tbody>

									@if(!empty($data))
									<?php $count = 1; ?>
									@foreach($data as $dt)
									<tr>
										<td>{{ $count++ }}</td>
										<td>{{ ucfirst($dt->name) }} {{ ucfirst($dt->lname) }}</td>
										<td>{{ $dt->email }}</td>
										<td>
											<span class="kt-switch kt-switch--sm">
												<label>
													<input type="checkbox" @if($dt->active == 1) checked @endif onchange="status('{{ $dt->id }}')" name="">
													<span></span>
												</label>
											</span>
										</td>
										<td>
											<a href="{{route('admin.edit',$dt->id)}}" class="btn btn-sm btn-clean btn-icon btn-icon-md" title="Edit" style="background: #968cbd;">
												<i class="la la-edit" style="color: white !important;"></i>
											</a>
										</td>
									</tr>
									@endforeach
									@endif
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script>
	$(document).ready(function() {
		$('#user_list').DataTable();
	});
</script>
<script>
	function status(id){
		$.ajax({
			type:'POST',
			url:"{{route('admin.status')}}",
			data:{
				'_token' : $('input[name="_token"]').val(),
				'id':id
			},
			success:function(data){
				if (data.status === 'status_changed') 
				{
					toastr.options.timeOut = 1500;
					toastr.options.fadeOut = 1500;
					toastr.options.progressBar = true;
					toastr.options.onHidden = function(){
					};

					toastr["success"]("Activation Status Changed", "Success");
				}
			}
		});

	}
</script>

@stop