routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
	return view('auth.login');
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('roles','RoleController');
Route::post('roles/update','RoleController@update')->name('update.roles');
Route::post('roles/edits','RoleController@edit')->name('roles.edits');
Route::any('roles/status','RoleController@status')->name('role.status');

Route::resource('user','UserController');
Route::post('user/delete','UserController@delete')->name('delete');
Route::post('user/indexs', 'UserController@index')->name('user.indexs');
Route::post('check/email','UserController@checkEmail')->name('check.email');
Route::any('user/status','UserController@status')->name('user.status');

Route::resource('admin','AdminController');
Route::post('admin/delete','AdminController@delete')->name('delete');
Route::post('check/admin/email','AdminController@checkEmail')->name('check.adminEmail');
Route::any('admin/status','AdminController@status')->name('admin.status');

Route::resource('banner','BannerController');
Route::post('banner/update','BannerController@update')->name('update.banner');
Route::post('banner/edits','BannerController@edit')->name('edits');
Route::any('banner/status','BannerController@status')->name('banner.status');

Route::resource('category','CategoryController');
Route::post('category/update','CategoryController@update')->name('update.category');
Route::post('category/edits','CategoryController@edit')->name('category.edits');
Route::any('category/status','CategoryController@status')->name('category.status');
Route::post('category/indexs', 'CategoryController@index')->name('category.indexs');
Route::post('category/delete','CategoryController@delete')->name('delete.category');
Route::post('check/catName','CategoryController@checkCatName')->name('check.catName');

Route::resource('subCategory','SubcategoryController');
Route::post('subCategory/update','SubcategoryController@update')->name('update.subCategory');
Route::post('subCategory/edits','SubcategoryController@edit')->name('subCategory.edits');
Route::any('subCategory/status','SubcategoryController@status')->name('subCategory.status');
Route::post('subCategory/indexs', 'SubcategoryController@index')->name('subCategory.indexs');
Route::post('subCategory/delete','SubcategoryController@delete')->name('delete.subCategory');
Route::post('check/subCatName','SubcategoryController@checkSubCatName')->name('check.subCatName');

Route::resource('course','CourseController');
Route::post('course/delete','CourseController@delete')->name('course.delete');
Route::any('course/status','CourseController@status')->name('course.status');
Route::any('course/homestatus','CourseController@homestatus')->name('course.homestatus');
Route::post('get/subCate', 'CourseController@getSubcate')->name('get.subCate');
Route::post('course/changeCommision', 'CourseController@changeCommision')->name('course.changeCommision');

Route::resource('staticPage','StaticPageController');
Route::post('staticPage/delete','StaticPageController@delete')->name('staticPage.delete');
Route::post('staticPage/indexs', 'StaticPageController@index')->name('staticPage.indexs');
Route::any('staticPage/status','StaticPageController@status')->name('staticPage.status');
Route::post('check/title','StaticPageController@checkTitle')->name('check.title');

Route::resource('testimonials','TestimonialsController');
Route::post('testimonials/delete','TestimonialsController@delete')->name('testimonials.delete');
Route::post('testimonials/indexs', 'TestimonialsController@index')->name('testimonials.indexs');
Route::any('testimonials/status','TestimonialsController@status')->name('testimonials.status');

Route::resource('profile','ProfileController');
Route::get('changePassword','ProfileController@changePassword')->name('changePassword');
Route::post('check/password','ProfileController@checkPassword')->name('check.password');

Route::resource('session','SessionController');
Route::post('session/delete','SessionController@delete')->name('session.delete');
Route::any('session/status','SessionController@status')->name('session.status');

Route::resource('review','ReviewController');
Route::post('review/update','ReviewController@update')->name('update.review');
Route::post('review/edits','ReviewController@edit')->name('review.edits');
Route::any('review/status','ReviewController@status')->name('review.status');
Route::post('review/indexs', 'ReviewController@index')->name('review.indexs');
Route::post('review/delete','ReviewController@delete')->name('delete.review');

Route::resource('payment','PaymentController');
Route::resource('redemption','RedemptionController');

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Role extends Model
{
	use SoftDeletes;
    protected $table = 'roles';
	protected $primaryKey = 'id';
	protected $guarded = ['id'];
}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Role;
use Str;
use DB;

class RoleController extends Controller
{
	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function __construct(Role $s)
	{
		$this->middleware('auth');
	}

	public function index()
	{
		$data['title'] = 'User Roles';
		$data['data'] = Role::get();
		return view('role.index')->with($data);
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create()
	{
		$data['title'] = "User Role";
		return view('role.create')->with($data);
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @return \Illuminate\Http\Response
	 */
	public function store(Request $request)
	{
		$param = $request->all();
		unset($param['user_id']);
		$param['slug'] = Str::slug($param['title']);
		$create = Role::create($param);
		if ($create) 
		{
			return redirect()->back();
		} 
		else 
		{
			return redirect()->back();
		}
	}


	public function status(Request $request)
	{
		$role = Role::where('id',$request->get('id'))->value('active');
		if($role == 1)
		{
			$update = Role::where('id',$request->get('id'))->update(['active' => 0]);
		}
		if($role == 0)
		{
			$update = Role::where('id',$request->get('id'))->update(['active' => 1]);
		}
		if($update)
		{
			return response()->json(['status' => 'status_changed']);
		}
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function show($id)
	{
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function edit(Request $request)
	{
		$data['title'] = "User Role";
		$data['role_data'] = Role::where('id',$request->get('id'))->first();
		return response()->json($data);
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function update(Request $request)
	{
		// $role = Role::findor
		$param['title'] = $request->title;
		$update = Role::where('id',$request->role_hidden_id)->update($param);
		return redirect()->back();
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function delete(Request $request)
	{
		
	}

	public function checkRole(Request $request)
	{
		$param = $request->all();
		if($param['title'] != ""){
			$param['title'] = Str::slug($param['title']);
			if($param['type'] == 'Add'){
				$check = Role::where('slug',$param['title'])->exists();
			}else{
				$check = Role::where('slug',$param['title'])->where('id','!=',$param['id'])->exists();
			}

			if($check){
				echo json_encode(false);
			}else{
				echo json_encode(true);
			}
		}
	}
}

resources/views/role/index.blade.php
@extends('main')
@section('content')

<div class="kt-content  kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor" id="kt_content"><br/>

	<div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">
		<div class="kt-portlet kt-portlet--mobile">
			<div class="kt-portlet__head kt-portlet__head--lg">
				<div class="kt-portlet__head-label">
					<span class="kt-portlet__head-icon">
						<i class="kt-font-brand flaticon2-line-chart"></i>
					</span>
					<h3 class="kt-portlet__head-title">
						{{ $title }} List
					</h3>
				</div>
				<div class="kt-portlet__head-toolbar">
					<div class="kt-portlet__head-wrapper">

						<div class="kt-portlet__head-actions">
							
							<a type="button" class="btn btn-brand btn-elevate btn-icon-sm" data-toggle="modal" data-target="#add_water" style="color: #ffffff;">
								<i class="la la-plus"></i>
								Add {{ $title }}
							</a>
							
						</div>
						
					</div>
				</div>
			</div>
			<div class="kt-portlet__body">
				<div id="kt_table_1_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
					<div class="row">
						<div class="col-sm-12">
							<table class="table table-striped- table-bordered table-hover table-checkable dataTable no-footer dtr-inline" id="user_list" role="grid" aria-describedby="kt_table_1_info">
								@csrf

								<thead>
									<tr role="row">
										<th>No</th>
										<th>User Role</th>
										<th>Activate Status</th>
										<th>Actions</th>
									</tr>
								</thead>
								<tbody>

									@if(!empty($data))
									<?php $count = 1; ?>
									@foreach($data as $dt)
									<tr>
										<td>{{ $count++ }}</td>
										<td>{{ ucfirst($dt->title) }}</td>
										<td>
											<span class="kt-switch kt-switch--sm">
												<label>
													<input type="checkbox" @if($dt->active == 1) checked @endif onchange="status('{{ $dt->id }}')" name="">
													<span></span>
												</label>
											</span>
										</td>
										<td>

											<a data-toggle="modal" data-target="#edit_water" onclick="edit('{{ $dt->id }}')" class="btn btn-sm btn-clean btn-icon btn-icon-md edit-icon" title="Edit" style="background: #968cbd;">
												<i class="la la-edit" style="color: #ffffff"></i>
											</a>

										</td>
									</tr>
									@endforeach
									@endif
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<!-- Add Modal-->
<div class="modal fade" id="add_water" tabindex="-1" role="dialog" aria-labelledby="staticBackdrop" aria-hidden="true">
	<div class="modal-dialog modal-dialog-scrollable modal-lg" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="exampleModalLabel">Add {{ $title }}</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<i aria-hidden="true" class="ki ki-close"></i>
				</button>
			</div>
			<form action="{{ route('roles.store') }}" method="post">
				@csrf
				<div class="modal-body">
					<div data-scroll="true" data-height="auto">
						<div class="form-group row">
							<label class="col-xl-3 col-lg-3 col-form-label">User Role</label>
							<div class="col-lg-9 col-xl-9">
								<input type="text" class="form-control" required="required" name="title" placeholder="Add User Role" autocomplete="off">
							</div>
						</div>
						<div class="modal-footer">
							<button type="button" class="btn btn-dark" data-dismiss="modal">Close</button>
							<button type="submit" class="btn btn-brand btn-elevate btn-icon-sm font-weight-bold">Add</button>
						</div>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>

<!--Edit Modal-->
<div class="modal fade" id="edit_water" tabindex="-1" role="dialog" aria-labelledby="staticBackdrop" aria-hidden="true">
	<div class="modal-dialog modal-dialog-scrollable modal-lg" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="exampleModalLabel">Edit {{ $title }}</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<i aria-hidden="true" class="ki ki-close"></i>
				</button>
			</div>
			<div class="modal-body">
				<form action="{{ route('update.roles') }}" method="post">
					@csrf
					<div data-scroll="true" data-height="auto">
						<div class="form-group row">
							<label class="col-xl-3 col-lg-3 col-form-label">User Role</label>
							<div class="col-lg-9 col-xl-9">
								<input type="hidden" name="role_hidden_id" value="" id="hidden_id">
								<input type="text" class="form-control" id="edit_role" required="required" name="title" placeholder="Add User Role" autocomplete="off">
							</div>
						</div>
						<div class="modal-footer">
							<button type="button" class="btn btn-dark" data-dismiss="modal">Close</button>
							<button type="submit" class="btn btn-brand btn-elevate btn-icon-sm font-weight-bold">Update</button>
						</div>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
<script>
	$(document).ready(function() {
		$('#user_list').DataTable();
	});
</script>
<script>
	function status(id){
		$.ajax({
			type:'POST',
			url:"{{route('role.status')}}",
			data:{
				'_token' : $('input[name="_token"]').val(),
				'id':id
			},
			success:function(data){
				if (data.status === 'status_changed') 
				{
					toastr.options.timeOut = 1500;
					toastr.options.fadeOut = 1500;
					toastr.options.progressBar = true;
					toastr.options.onHidden = function(){
						// location.reload();
					};

					toastr["success"]("Activation Status Changed", "Success");
				}
			}
		});
	}	

	function edit(id){

		$.ajax({
			type: "post",
			url: "{{ route('roles.edits') }}",
			data: {
				'_token': $('input[name="_token"]').val(),
				'id': id
			},
			cache: false,
			success: function (data)
			{
				$('#hidden_id').val(data.role_data['id']);
				$('#edit_role').val(data.role_data['title']);
			}
		});
	}

	
	
</script>

@stop